### ISSUE TITLE
[Tracking] Operation Playground

### ISSUE THREAD

**Issue by crutchcorn** [playfulprogramming/playfulprogramming#1114]
- [x] Write article(s)
    - [x] Announcement
    - [x] History
    - [ ] Analytics (@crutchcorn's personal on dev . to)
- [x] Change `unicorns` -> `people`
    - [x] Redirect
    - [x] Route
- [x] Change codebase internals
- [ ] Update logo
    - [ ] Design
    - [ ] Code
    - [ ] Add to end of announcement article
- [x] Add new "Join us" page
    - [x] Design
    - [x] Code
        - [x] Headings/A11Y
        - [x] Reduced motion
        - [x] Add to site navbar
        - [x] Title flair
        - [x] Illustrations
- [x] Add announcement banner to site
    - [x] Design
    - [x] Code
- [x] Change socials
    - [x] GitHub Org
    - [x] GitHub Repo
    - [x] Twitter/X
    - [x] Mastodon
    - [x] LinkedIn (after rebrand, they require an announcement post)
    - [x] Facebook
    - [x] Discord
    - [x] OpenCollective
    - [x] YouTube
- [x] Update Google Search Console
- [x] Update Plausible
- [x] Update Google Domains email
- [x] Copy Vercel DNS settings
- [x] Domain
- [x] Update ConvertKit
- [x] 301 old domain
- [x] Update framework.guide and fundamentals.framework.guide redirects
- [x] `UNICORN-UMPIRE` discord role -> `PLAYGROUND-PROTECTOR`
- [x] Change share image
